version: '3'

services:
  server:
    image: nginx:alpine
    container_name: webserver
    restart: always
    ports:
      - 90:80
    networks:
      - webserver
    container_name: webserver
    volumes:
      - ./app_data:/app_data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  webserver:
    driver: bridge
